import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/ASUS1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const page=await browser.newPage();page.setDefaultTimeout(7000);
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.addInitScript(()=>localStorage.clear());
await page.goto(process.env.SMOKE_URL||'http://127.0.0.1:4178/index.html',{waitUntil:'networkidle'});
await page.click('[data-role="parent"]');await page.fill('#pinInput','1234');await page.click('#loginBtn');await page.waitForSelector('.parent-home');
const labels=await page.locator('.tab:not(.hidden)').allTextContents();if(labels.join(',')!=='陪练,首页,我的')throw new Error('Unexpected parent navigation: '+labels.join(','));
if((await page.locator('#todayList').innerText()).includes('乐乐'))throw new Error('Parent saw another child task');
if(await page.locator('.home-check').count())throw new Error('Unsigned fallback family tasks were shown');
if((await page.locator('#tabContent').innerText()).includes('当前能力')||(await page.locator('#tabContent').innerText()).includes('基线 vs'))throw new Error('Training accuracy was presented as ability change');
await page.evaluate(()=>{enhancedState.consents.push({id:'test-consent',childId:'c1',version:'1.0-demo',status:'active',scope:['training'],confirmedBy:'parent',ts:Date.now()});enhancedState.planVersions.push({id:'test-plan',childId:'c1',version:99,status:'effective',rows:[{moduleId:'P01',moduleName:'颜色识别',delivery:'online',difficulty:2,duration:5},{moduleId:'M01',moduleName:'物品配对',delivery:'online',difficulty:2,duration:5}],signature:{signedBy:'测试康复师',role:'teacher',signedAt:Date.now()},ts:Date.now()});saveEnhanced();showTab('report');});
await page.waitForSelector('.home-check');if(await page.locator('.home-check').count()!==2)throw new Error('Parent did not receive exactly the signed tasks');
await page.locator('.home-check input').first().check();await page.evaluate(()=>showTab('report'));if(!await page.locator('.home-check input').first().isChecked())throw new Error('Home task completion was not persisted');
await page.click('[data-tab="train"]');if(await page.locator('.module-card').count()!==2)throw new Error('Parent training map was not restricted to the signed plan');
const gates=await page.evaluate(()=>({other:trainingGate('c2','P03'),outside:trainingGate('c1','P03')}));if(gates.other.ok||!gates.other.reason.includes('数据授权'))throw new Error('Cross-child gate failed');if(gates.outside.ok||!gates.outside.reason.includes('不在当前已签署'))throw new Error('Plan allowlist gate failed');
await page.evaluate(()=>{enhancedState.riskFlags.push({id:'risk-test',childId:'c1',type:'fall',label:'跌倒风险',status:'active',ts:Date.now()});saveEnhanced();showTab('report');});await page.waitForSelector('.parent-summary-grid .alert');if(!(await page.locator('.parent-summary-grid .alert').innerText()).includes('请暂停训练'))throw new Error('Safety risk did not override the parent status');
await page.click('[data-tab="setting"]');await page.click('[data-panel="consent"]');await page.waitForSelector('#saveConsent');await page.check('[data-consent-scope="training"]');await page.check('[data-consent-scope="assessment"]');await page.click('#saveConsent');await page.waitForSelector('#revokeConsent');const consent=await page.evaluate(()=>enhancedState.consents.find(x=>x.childId==='c1'&&x.status==='active'));if(!consent||consent.scope.join(',')!=='training,assessment')throw new Error('Granular consent was not saved');
if(errors.length)throw new Error(errors.join('\n'));
console.log('Parent safety passed: scoped tasks, plan allowlist, risk priority, persistent completion, consent, and parent wording.');
await browser.close();